config/routes.rb
Rails.application.routes.draw do
  resources :customers
  root 'customers#new'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :model
  belongs_to :shop
end

app/models/model.rb
class Model < ActiveRecord::Base
end

app/models/shop.rb
class Shop < ActiveRecord::Base
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
  after_create :add_tenant_to_apartment

  def self.current
    tenant = Tenant.find_by domain:Apartment::Tenant.current
    raise ::Apartment::TenantNotFound, "Unable to find tenant" unless tenant
    tenant
  end

  def switch!
    Apartment::Tenant.switch! domain
  end

  private
  def add_tenant_to_apartment
    Apartment::Tenant.create(domain)
  end

  def drop_tenant_from_apartment
    Apartment::Tenant.drop(domain)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :phone, :email, :model_id, :shop_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def background_image_url
    Tenant.current.image_url
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= simple_form_for(@customer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :phone %>
    <%= f.input :email %>
    <%= f.association :model %>
    <%= f.association :shop %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Model</th>
      <th>Shop</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.phone %></td>
        <td><%= customer.email %></td>
        <td><%= customer.model %></td>
        <td><%= customer.shop %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<%= simple_form_for(@customer) do |f| %>
    <div class="modal fade" id="myModal">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h3 class="modal-title">Welcome to <%= Tenant.current.name%></h3>
            <h5>Please sign in and choose your repair facility</h5>
          </div>
          <div class="modal-body">
            <%= f.error_notification %>
            <div class="form-inputs">
              <%= f.input :name %>
              <%= f.input :phone %>
              <%= f.input :email %>
              <%= f.association :model %>
              <%= f.association :shop %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <%= f.button :submit, "Schedule My Appointment!", class:%w(btn btn-success) %>
          </div>
        </div>
      </div>
    </div>
<% end %>

<script type="text/javascript">
  $(window).load(function(){
    $('#myModal').modal('show');
  });
</script>

app/views/customers/show.html.erb
<div class='panel panel-default text-center'>
  <h1>Thank you!</h1>
  <h2>We will contact you soon with your appointment.</h2>
  <a href="/">Home</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AutoRepairs</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body style = "background-image:url('<%= background_image_url %>'); background-size:cover">
<%= yield %>

</body>
</html>